### ISSUE TITLE
Separate hospital beds and hotel beds

### ISSUE THREAD

**Issue by hktang** [hktang/covid-hyogo#11]
As data on hospital beds and hotel beds are provided separately, why not show these numbers separately too?

**Comment by akiya64** [comment]
Hi, I recounted beds in this spreadsheet since 1 march, separate hospital and hotels.
https://docs.google.com/spreadsheets/d/1isVLTh9OA-ZoCwueFdxcEO_A46wjNfwfuq77c6NH0nI/edit?usp=sharing
If you need, you can import it.

And, I will consider showing beds count separately too.

**Comment by hktang** [comment]
This is really useful information. Will definitely include it in the master spreadsheet. Thank you so much for collecting the information!

**Comment by hktang** [comment]
Hi @akiya64, 

You might have noticed a refactoring to the code, and the app now reads data from the `src/data` folder. There, hospital bed information is included from the Status Sheet. With this data, I've come up with an updated chart at the development branch: https://covid-hyogo-r7dsidpb4.now.sh/

Before merging into Master, it would be great if you could have a look. I am struggling with the series labels and the data points, especially when we have to take into account both mobile and desktop views. If you have any suggestions that would be great. 

![Screenshot_2020-04-26 COVID-19 in Hyogo, Japan](https://user-images.githubusercontent.com/2219830/80311144-ddccca80-8818-11ea-87d3-6fa7a7a56bf7.png)
